name: CI/CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8
          flake8 .

      - name: Build & push Docker image
        env:
          REGISTRY: ghcr.io
          IMAGE: ${{ github.repository }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
          docker build . -t $REGISTRY/${IMAGE}:latest
          docker push $REGISTRY/${IMAGE}:latest

      - name: Trigger Render Deploy via Hook
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "$DEPLOY_HOOK"
